### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by amitmishra11** [Sanket1308/analog-clock#11]
@sanket please assign this to me

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀

**Comment by Skysparko** [comment]
@Sanket1308 hey can I work on it?

**Comment by Sanket1308** [comment]
@Skysparko It's already assigned. I'll assign you if he doesn't complete in 24 hours. Till then work on other issues.
Find more issues here:
https://github.com/Sanket1308/Weather-App/
https://github.com/Sanket1308/javascript-quote-generator
https://github.com/Sanket1308/website-authentication-process
https://github.com/Sanket1308/Simple-Calculator
https://github.com/Sanket1308/analog-clock
https://github.com/Sanket1308/bots-collection

**Comment by Skysparko** [comment]
ok
