### ISSUE TITLE
Change the position of Dark mode toggle

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/analog-clock#29]
Change the position of Dark mode toggle
- Now, it's at bottom left
- Keep it upper right

![Screenshot (1114)](https://user-images.githubusercontent.com/79108273/194732581-fdc4c84c-36fc-42c9-bf55-3a758a78f921.png)

**Comment by Sakshi-75** [comment]
Hi @Sanket1308 ,
Can I work on this?

**Comment by mehraankush** [comment]
i will do that .

**Comment by Sanket1308** [comment]
Go ahead, @Sakshi-75! Contribute well🚀

**Comment by Sanket1308** [comment]
@mehraankush , thanks for your interest!

We're assigning issues on a first come first serve basis. If @Sakshi-75  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).
