### ISSUE TITLE
Add minutes sign around the clock

### ISSUE THREAD

**Issue by Sanket1308** [Sanket1308/analog-clock#7]
Add minutes sign around the clock
- 60 lines of 60 minutes around the inner circumference of clock

**Comment by tsari02** [comment]
Please assign this issue to me.

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀

**Comment by Eli4479** [comment]
> Add minutes sign around the clock
> 
> * 60 lines of 60 minutes around the inner circumference of clock

yes I can add line of Minute assign it to me

**Comment by Sanket1308** [comment]
Completed!
